<?php

return [
  'dynamic_content'        => true,
  'cornerstone_favicon'    => false,
  'workspace_side'         => get_option('cs_workspace_position_default', 'right'),
  'workspace_outline_display' => 'nested',
  'show_wp_toolbar'        => false,
  'rich_text_default'      => true,
  'preferences_in_toolbar' => true,
  'context_menu'           => true,
  'ui_theme'               => 'dark',
  'status_indicators'      => 'all',
  'preserve_nav_group'     => false,
  'code_editors'           => true,
  'dev_toolkit'            => false,
  'custom_app_css'         => '',
  'preview_inset'          => false,
  'document_list_show_all' => true,
  'document_list_limit'    => 100,
  'default_layout_element' => 'section',
  'use_max'                => apply_filters("cs_max_enabled", true),
  'element_favorites'      => [],
  'insert_use_element_library' => false,
  'show_element_icons'     => true,
  'expanded_font_family' => false,
  'autosave' => false,
];
